[BBCSPA-2608] Remove unused z-index for Itinerary
blablacar/ui-library pull request #169
Opened 2019-01-17 16:56 UTC by Tip-Sy

<img width="654" alt="capture d ecran 2019-01-17 a 17 46 58" src="https://user-images.githubusercontent.com/7479808/51334931-27a8fb80-1a81-11e9-959e-d52f62c8f494.png">

2019-01-17 16:59 UTC, wakooka requested changes
Changelog  ;)

2019-01-18 09:46 UTC, Tuxosaurus approved these changes

2019-01-18 09:48 UTC, pith approved these changes

2019-01-18 09:48 UTC, pith commented on src/itinerary/style.ts
> -    z-index: 1;
Sure that it's not need for the search page ?

2019-01-18 10:27 UTC, wakooka approved these changes

2019-01-18 10:28 UTC, merged