[BBCSPA-3528] Update Node version to 10.15.0
blablacar/ui-library pull request #337
Opened 2019-07-30 15:58 UTC by Tip-Sy

Node 10.x.x uses a new implementation for date formatting, so I'm forcing the basic date format specified here: https://www.ecma-international.org/ecma-402/1.0/#BasicFormatMatcher

Seen in the doc:
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Date/toLocaleDateString

2019-07-30 15:59 UTC, wakooka approved these changes

2019-07-30 16:52 UTC, grosbouddha approved these changes

2019-07-31 12:16 UTC, pith requested changes
Also change the version in `travis.yml`

2019-07-31 12:29 UTC, pith approved these changes

2019-07-31 13:52 UTC, grosbouddha commented on src/timePicker/index.tsx
> + * so we don't rely on it and check the locale for 24-hour format.
Please add a comment to TimePickerProps#renderTime:
'Custom renderTime. If not provided a default one without proper i18n will be used.'

2019-07-31 13:52 UTC, grosbouddha approved these changes

2019-07-31 16:48 UTC, merged